#
# Copyright (c) 2024–2025, Daily
#
# SPDX-License-Identifier: BSD 2-Clause License
#

"""pipecat-quickstart - Pipecat Voice Agent

This bot uses a cascade pipeline: Speech-to-Text → LLM → Text-to-Speech

Generated by Pipecat CLI

Required AI services:
- Deepgram (Speech-to-Text)
- Google (LLM)
- Cartesia (Text-to-Speech)

Run the bot using::

    uv run bot.py
"""

import os
import time

from dotenv import load_dotenv
from loguru import logger
from pipecat.audio.vad.silero import SileroVADAnalyzer
from pipecat.frames.frames import Frame, LLMFullResponseEndFrame, LLMRunFrame, LLMTextFrame, TranscriptionFrame
from pipecat.pipeline.pipeline import Pipeline
from pipecat.processors.frame_processor import FrameDirection, FrameProcessor
from pipecat.pipeline.worker import PipelineParams, PipelineWorker
from pipecat.processors.aggregators.llm_context import LLMContext
from pipecat.processors.aggregators.llm_response_universal import (
    LLMContextAggregatorPair,
    LLMUserAggregatorParams,
)
from pipecat.runner.types import RunnerArguments
from pipecat.runner.utils import create_transport
from pipecat.processors.frameworks.rtvi import RTVIObserverParams, RTVIFunctionCallReportLevel
from providers.llm.factory import get_llm
from providers.stt.factory import get_stt
from providers.tts.factory import get_tts
from pipecat.transports.base_transport import BaseTransport, TransportParams
from pipecat.transports.daily.transport import DailyParams
from pipecat.workers.runner import WorkerRunner
from memory import build_memory_messages, build_turn_memory_context, load_memory_bundle, save_conversation_message
from memory_config import MEMORY_EMBEDDING_DIMENSION
from rag import build_rag_context
from rag_config import RAG_VOICE_QUERY_WINDOW_SECONDS
from tools.tavily import tavily_search

load_dotenv(override=True)


class ConversationMemoryProcessor(FrameProcessor):
    def __init__(self, conversation_id: int | None, capture: str, **kwargs):
        super().__init__(**kwargs)
        self._conversation_id = conversation_id
        self._capture = capture
        self._assistant_chunks: list[str] = []

    async def process_frame(self, frame: Frame, direction: FrameDirection):
        await super().process_frame(frame, direction)

        if (
            direction == FrameDirection.DOWNSTREAM
            and self._capture == "user"
            and isinstance(frame, TranscriptionFrame)
        ):
            await save_conversation_message(self._conversation_id, "You", frame.text)
        elif (
            direction == FrameDirection.DOWNSTREAM
            and self._capture == "assistant"
            and isinstance(frame, LLMTextFrame)
        ):
            self._assistant_chunks.append(frame.text)
        elif (
            direction == FrameDirection.DOWNSTREAM
            and self._capture == "assistant"
            and isinstance(frame, LLMFullResponseEndFrame)
        ):
            assistant_text = "".join(self._assistant_chunks).strip()
            self._assistant_chunks.clear()
            await save_conversation_message(self._conversation_id, "Aura", assistant_text)

        await self.push_frame(frame, direction)


class MemoryRetrievalProcessor(FrameProcessor):
    def __init__(self, user_id: int | None, context: LLMContext, **kwargs):
        super().__init__(**kwargs)
        self._user_id = user_id
        self._context = context

    async def process_frame(self, frame: Frame, direction: FrameDirection):
        await super().process_frame(frame, direction)

        if (
            direction == FrameDirection.DOWNSTREAM
            and self._user_id
            and isinstance(frame, TranscriptionFrame)
        ):
            memory_context = await build_turn_memory_context(self._user_id, frame.text)
            if memory_context:
                self._context.add_message({"role": "developer", "content": memory_context})

        await self.push_frame(frame, direction)


class RollingVoiceQueryBuffer:
    def __init__(self, window_seconds: float = RAG_VOICE_QUERY_WINDOW_SECONDS):
        self._window_seconds = window_seconds
        self._items: list[tuple[float, str]] = []

    def add(self, text: str, now: float | None = None) -> str:
        now = time.monotonic() if now is None else now
        text = (text or "").strip()
        if text:
            self._items.append((now, text))
        self._items = [
            (timestamp, value)
            for timestamp, value in self._items
            if now - timestamp <= self._window_seconds
        ]
        return " ".join(value for _, value in self._items)

    def clear(self) -> None:
        self._items.clear()


class RagRetrievalProcessor(FrameProcessor):
    def __init__(self, user_id: int | None, context: LLMContext, **kwargs):
        super().__init__(**kwargs)
        self._user_id = user_id
        self._context = context
        self._query_buffer = RollingVoiceQueryBuffer()

    async def process_frame(self, frame: Frame, direction: FrameDirection):
        await super().process_frame(frame, direction)

        if (
            direction == FrameDirection.DOWNSTREAM
            and self._user_id
            and isinstance(frame, TranscriptionFrame)
        ):
            combined_query = self._query_buffer.add(frame.text)
            rag_context = await build_rag_context(self._user_id, combined_query)
            if rag_context:
                self._context.add_message({"role": "developer", "content": rag_context})
        elif direction == FrameDirection.DOWNSTREAM and isinstance(frame, LLMFullResponseEndFrame):
            self._query_buffer.clear()

        await self.push_frame(frame, direction)


async def run_bot(transport: BaseTransport, runner_args: RunnerArguments) -> None:
    """Run the voice bot for this session.

    Args:
        transport: The transport for this session, built by ``create_transport``
            (or by hand for the dial-out/SIP production flows).
        runner_args: Runner session arguments. Carries the request ``body``
            (e.g. dial-out settings, SIP call details) and ``session_id``; the
            standard web/telephony pipelines don't need it.
    """
    logger.info("Starting bot")

    # Speech-to-Text service
    stt = get_stt()

    # Text-to-Speech service
    tts = get_tts()

    # LLM service
    llm = get_llm()

    memory_bundle = await load_memory_bundle(runner_args.body)
    memory_messages = build_memory_messages(memory_bundle)
    if memory_bundle:
        logger.info(
            f"Loaded memory for user={memory_bundle.user.id} "
            f"conversation={memory_bundle.conversation.id} "
            f"facts={len(memory_bundle.facts)} recent_messages={len(memory_bundle.recent_messages)}"
        )
    conversation_id = memory_bundle.conversation.id if memory_bundle else None
    user_id = memory_bundle.user.id if memory_bundle else None
    user_memory = ConversationMemoryProcessor(conversation_id, capture="user", name="UserMemory")
    assistant_memory = ConversationMemoryProcessor(
        conversation_id,
        capture="assistant",
        name="AssistantMemory",
    )

    context = LLMContext(
        messages=memory_messages,
        tools=[tavily_search]
    )
    memory_retrieval = MemoryRetrievalProcessor(user_id, context, name="MemoryRetrieval")
    rag_retrieval = RagRetrievalProcessor(user_id, context, name="RagRetrieval")
    user_aggregator, assistant_aggregator = LLMContextAggregatorPair(
        context,
        user_params=LLMUserAggregatorParams(
            vad_analyzer=SileroVADAnalyzer(),
        ),
    )

    # Pipeline - assembled from reusable components
    pipeline = Pipeline(
        [
            transport.input(),
            stt,
            user_memory,
            memory_retrieval,
            rag_retrieval,
            user_aggregator,
            llm,
            assistant_memory,
            tts,
            transport.output(),
            assistant_aggregator,
        ]
    )

    worker = PipelineWorker(
        pipeline,
        params=PipelineParams(
            enable_metrics=True,
            enable_usage_metrics=True,
        ),
        rtvi_observer_params=RTVIObserverParams(
            function_call_report_level={"*": RTVIFunctionCallReportLevel.FULL}
        ),
        observers=[],
    )

    @worker.rtvi.event_handler("on_client_ready")
    async def on_client_ready(rtvi):
        # Kick off the conversation
        greeting_instruction = "Just say hello."
        if memory_bundle and (memory_bundle.summary or memory_bundle.recent_messages):
            greeting_instruction = (
                "Briefly greet the user and continue naturally with awareness of the "
                "loaded conversation context. Do not recap unless the user asks."
            )
        context.add_message({"role": "developer", "content": greeting_instruction})
        await worker.queue_frames([LLMRunFrame()])

    @transport.event_handler("on_client_connected")
    async def on_client_connected(transport, client):
        logger.info("Client connected")

    @transport.event_handler("on_client_disconnected")
    async def on_client_disconnected(transport, client):
        logger.info("Client disconnected")
        await worker.cancel()

    runner = WorkerRunner(handle_sigint=False)

    await runner.add_workers(worker)
    await runner.run()


async def bot(runner_args: RunnerArguments):
    """Main bot entry point."""

    transport_params = {
        "daily": lambda: DailyParams(
            audio_in_enabled=True,
            audio_out_enabled=True,
        ),
        "webrtc": lambda: TransportParams(
            audio_in_enabled=True,
            audio_out_enabled=True,
        ),
    }

    transport = await create_transport(runner_args, transport_params)

    await run_bot(transport, runner_args)


if __name__ == "__main__":
    from pipecat.runner.run import app, main
    from auth import router as auth_router
    from history import router as history_router
    from memories import router as memories_router
    from rag_files import router as rag_files_router
    
    # Mount the authentication routes
    app.include_router(auth_router)
    app.include_router(history_router)
    app.include_router(memories_router)
    app.include_router(rag_files_router)
    
    # Initialize the database on startup
    @app.on_event("startup")
    async def startup_event():
        from database import engine, Base
        async with engine.begin() as conn:
            from sqlalchemy import text
            await conn.execute(text("CREATE EXTENSION IF NOT EXISTS vector"))
            await conn.run_sync(Base.metadata.create_all)
            await conn.execute(text("ALTER TABLE conversations ADD COLUMN IF NOT EXISTS summary TEXT DEFAULT ''"))
            await conn.execute(text("ALTER TABLE conversations ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT NOW()"))
            await conn.execute(text("UPDATE conversations SET updated_at = created_at WHERE updated_at IS NULL"))
            await conn.execute(text("ALTER TABLE user_memories ADD COLUMN IF NOT EXISTS fact_type VARCHAR DEFAULT 'profile' NOT NULL"))
            await conn.execute(text("ALTER TABLE user_memories ADD COLUMN IF NOT EXISTS durability VARCHAR DEFAULT 'stable' NOT NULL"))
            await conn.execute(text("ALTER TABLE user_memories ADD COLUMN IF NOT EXISTS status VARCHAR DEFAULT 'active' NOT NULL"))
            await conn.execute(text("UPDATE user_memories SET fact_type = 'profile' WHERE fact_type IS NULL"))
            await conn.execute(text("UPDATE user_memories SET durability = 'stable' WHERE durability IS NULL"))
            await conn.execute(text("UPDATE user_memories SET status = 'active' WHERE status IS NULL"))
            await conn.execute(text("UPDATE user_memories SET key = 'real_name' WHERE key = 'name'"))
            await conn.execute(text("ALTER TABLE user_memories DROP CONSTRAINT IF EXISTS uq_user_memory_key"))
            await conn.execute(text(
                """
                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1
                        FROM pg_constraint
                        WHERE conname = 'uq_user_memory_fact_value'
                    ) THEN
                        ALTER TABLE user_memories
                        ADD CONSTRAINT uq_user_memory_fact_value
                        UNIQUE (user_id, fact_type, key, value);
                    END IF;
                END $$;
                """
            ))
            try:
                await conn.execute(text("DROP INDEX IF EXISTS idx_memory_chunks_embedding"))
                await conn.execute(text(
                    f"""
                    UPDATE memory_chunks
                    SET embedding = NULL
                    WHERE embedding IS NOT NULL
                      AND vector_dims(embedding) != {MEMORY_EMBEDDING_DIMENSION}
                    """
                ))
                await conn.execute(text(
                    f"""
                    ALTER TABLE memory_chunks
                    ALTER COLUMN embedding TYPE vector({MEMORY_EMBEDDING_DIMENSION})
                    USING embedding::vector({MEMORY_EMBEDDING_DIMENSION})
                    """
                ))
                await conn.execute(text(
                    "CREATE INDEX IF NOT EXISTS idx_memory_chunks_embedding "
                    "ON memory_chunks USING ivfflat (embedding vector_cosine_ops) WITH (lists = 100)"
                ))
            except Exception as exc:
                logger.warning(
                    "pgvector setup skipped. Ensure the Postgres container uses "
                    "pgvector/pgvector:pg15 and MEMORY_EMBEDDING_DIMENSION matches "
                    f"your embedding provider. Error: {exc}"
                )
            try:
                await conn.execute(text(
                    f"""
                    UPDATE rag_chunks
                    SET embedding = NULL
                    WHERE embedding IS NOT NULL
                      AND vector_dims(embedding) != {MEMORY_EMBEDDING_DIMENSION}
                    """
                ))
                await conn.execute(text(
                    f"""
                    ALTER TABLE rag_chunks
                    ALTER COLUMN embedding TYPE vector({MEMORY_EMBEDDING_DIMENSION})
                    USING embedding::vector({MEMORY_EMBEDDING_DIMENSION})
                    """
                ))
                await conn.execute(text(
                    "CREATE INDEX IF NOT EXISTS idx_rag_chunks_embedding "
                    "ON rag_chunks USING hnsw (embedding vector_cosine_ops)"
                ))
                await conn.execute(text(
                    "CREATE INDEX IF NOT EXISTS idx_rag_chunks_search_vector "
                    "ON rag_chunks USING GIN (search_vector)"
                ))
                await conn.execute(text(
                    "CREATE INDEX IF NOT EXISTS idx_rag_files_user_status "
                    "ON rag_files (user_id, status)"
                ))
                await conn.execute(text(
                    "CREATE INDEX IF NOT EXISTS idx_rag_chunks_user_file "
                    "ON rag_chunks (user_id, file_id)"
                ))
            except Exception as exc:
                logger.warning(f"RAG index setup skipped: {exc}")

    main()
