#
# Copyright (c) 2024–2025, Daily
#
# SPDX-License-Identifier: BSD 2-Clause License
#

"""pipecat-quickstart - Pipecat Voice Agent

This bot uses a cascade pipeline: Speech-to-Text → LLM → Text-to-Speech

Generated by Pipecat CLI

Required AI services:
- Deepgram (Speech-to-Text)
- Google (LLM)
- Cartesia (Text-to-Speech)

Run the bot using::

    uv run bot.py
"""

import asyncio
import json
import os
import time

from dotenv import load_dotenv
from loguru import logger
from pipecat.audio.vad.silero import SileroVADAnalyzer
from pipecat.frames.frames import (
    Frame,
    LLMFullResponseEndFrame,
    LLMRunFrame,
    LLMTextFrame,
    OutputTransportMessageFrame,
    TranscriptionFrame,
    FunctionCallInProgressFrame,
    TTSSpeakFrame,
)
from pipecat.pipeline.pipeline import Pipeline
from pipecat.processors.frame_processor import FrameDirection, FrameProcessor
from pipecat.pipeline.worker import PipelineParams, PipelineWorker
from pipecat.processors.aggregators.llm_context import LLMContext
from pipecat.processors.aggregators.llm_response_universal import (
    LLMContextAggregatorPair,
    LLMUserAggregatorParams,
)
from pipecat.runner.types import RunnerArguments
from pipecat.runner.utils import create_transport
from pipecat.processors.frameworks.rtvi import RTVIObserverParams, RTVIFunctionCallReportLevel
from providers.llm.factory import get_llm
from providers.stt.factory import get_stt
from providers.tts.factory import get_tts
from pipecat.transports.base_transport import BaseTransport, TransportParams
from pipecat.transports.daily.transport import DailyParams
from pipecat.workers.runner import WorkerRunner
from services.memory import build_memory_messages, build_turn_memory_context, load_memory_bundle, save_conversation_message
from core.memory_config import MEMORY_EMBEDDING_DIMENSION
from services.rag import build_rag_context_with_payload, is_rag_query
from core.rag_config import RAG_VOICE_QUERY_WINDOW_SECONDS
from tools.tavily import tavily_search
from tools.raise_issue import raise_issue

load_dotenv(override=True)

from core.processors import (
    ConversationMemoryProcessor,
    ToolFillerProcessor,
    ContextRetrievalProcessor,
)


async def run_bot(transport: BaseTransport, runner_args: RunnerArguments) -> None:
    """Run the voice bot for this session.

    Args:
        transport: The transport for this session, built by ``create_transport``
            (or by hand for the dial-out/SIP production flows).
        runner_args: Runner session arguments. Carries the request ``body``
            (e.g. dial-out settings, SIP call details) and ``session_id``; the
            standard web/telephony pipelines don't need it.
    """
    logger.info("Starting bot")

    # Speech-to-Text service
    stt = get_stt()

    # Text-to-Speech service
    tts = get_tts()

    # LLM service
    llm = get_llm()

    memory_bundle = await load_memory_bundle(runner_args.body)
    memory_messages = build_memory_messages(memory_bundle)
    if memory_bundle:
        logger.info(
            f"Loaded memory for user={memory_bundle.user.id} "
            f"conversation={memory_bundle.conversation.id} "
            f"facts={len(memory_bundle.facts)} recent_messages={len(memory_bundle.recent_messages)}"
        )
    conversation_id = memory_bundle.conversation.id if memory_bundle else None
    user_id = memory_bundle.user.id if memory_bundle else None
    user_memory = ConversationMemoryProcessor(conversation_id, capture="user", name="UserMemory")
    assistant_memory = ConversationMemoryProcessor(
        conversation_id,
        capture="assistant",
        name="AssistantMemory",
    )

    context = LLMContext(
        messages=memory_messages,
        tools=[tavily_search, raise_issue]
    )
    context_retrieval = ContextRetrievalProcessor(user_id, conversation_id, context, name="ContextRetrieval")
    user_aggregator, assistant_aggregator = LLMContextAggregatorPair(
        context,
        user_params=LLMUserAggregatorParams(
            vad_analyzer=SileroVADAnalyzer(),
        ),
    )

    tool_filler = ToolFillerProcessor(name="ToolFiller")

    # Pipeline - assembled from reusable components
    pipeline = Pipeline(
        [
            transport.input(),
            stt,
            user_memory,
            context_retrieval,
            user_aggregator,
            llm,
            tool_filler,
            assistant_memory,
            tts,
            transport.output(),
            assistant_aggregator,
        ]
    )

    worker = PipelineWorker(
        pipeline,
        params=PipelineParams(
            enable_metrics=True,
            enable_usage_metrics=True,
        ),
        rtvi_observer_params=RTVIObserverParams(
            function_call_report_level={"*": RTVIFunctionCallReportLevel.FULL}
        ),
        observers=[],
    )

    @worker.rtvi.event_handler("on_client_ready")
    async def on_client_ready(rtvi):
        # Kick off the conversation
        greeting_instruction = "Just say hello."
        if memory_bundle and (memory_bundle.summary or memory_bundle.recent_messages):
            greeting_instruction = (
                "Briefly greet the user and continue naturally with awareness of the "
                "loaded conversation context. Do not recap unless the user asks."
            )
        context.add_message({"role": "developer", "content": greeting_instruction})
        await worker.queue_frames([LLMRunFrame()])

    @transport.event_handler("on_client_connected")
    async def on_client_connected(transport, client):
        logger.info("Client connected")

    @transport.event_handler("on_client_disconnected")
    async def on_client_disconnected(transport, client):
        logger.info("Client disconnected")
        await worker.cancel()

    runner = WorkerRunner(handle_sigint=False)

    await runner.add_workers(worker)
    await runner.run()


async def bot(runner_args: RunnerArguments):
    """Main bot entry point."""

    transport_params = {
        "daily": lambda: DailyParams(
            audio_in_enabled=True,
            audio_out_enabled=True,
        ),
        "webrtc": lambda: TransportParams(
            audio_in_enabled=True,
            audio_out_enabled=True,
        ),
    }

    transport = await create_transport(runner_args, transport_params)

    await run_bot(transport, runner_args)


from fastapi import APIRouter
health_router = APIRouter(tags=["health"])

@health_router.get("/health/live")
async def liveness_probe():
    return {"status": "alive"}

@health_router.get("/health/ready")
async def readiness_probe():
    # In a real app, you might check DB connectivity here
    return {"status": "ready"}



if __name__ == "__main__":
    from pipecat.runner.run import app, main
    from fastapi.middleware.cors import CORSMiddleware
    import os

    allowed_origins_str = os.getenv("ALLOWED_ORIGINS", "http://localhost:5173,http://localhost:80")
    allowed_origins = [origin.strip() for origin in allowed_origins_str.split(",")]

    app.add_middleware(
        CORSMiddleware,
        allow_origins=allowed_origins,
        allow_credentials=True,
        allow_methods=["*"],
        allow_headers=["*"],
    )

    from api.auth import router as auth_router
    from api.history import router as history_router
    from api.memories import router as memories_router
    from api.rag_files import router as rag_files_router
    
    app.include_router(auth_router)
    app.include_router(history_router)
    app.include_router(memories_router)
    app.include_router(rag_files_router)
    app.include_router(health_router)
    
    from contextlib import asynccontextmanager
    
    # Initialize the background task queue
    @asynccontextmanager
    async def lifespan(app):
        from core.task_queue import task_queue
        task_queue.start(num_workers=3)
        yield
        await task_queue.stop()

    app.router.lifespan_context = lifespan

    main()
