#
# Copyright (c) 2024–2025, Daily
#
# SPDX-License-Identifier: BSD 2-Clause License
#

"""pipecat-quickstart - Pipecat Voice Agent

This bot uses a cascade pipeline: Speech-to-Text → LLM → Text-to-Speech

Generated by Pipecat CLI

Required AI services:
- Deepgram (Speech-to-Text)
- Google (LLM)
- Cartesia (Text-to-Speech)

Run the bot using::

    uv run bot.py
"""

import asyncio
import json
import os
import time

from dotenv import load_dotenv
from loguru import logger
from pipecat.audio.vad.vad_analyzer import VADParams
from pipecat.audio.turn.smart_turn.base_smart_turn import SmartTurnParams
from pipecat.frames.frames import (
    Frame,
    LLMFullResponseEndFrame,
    LLMTextFrame,
    OutputTransportMessageFrame,
    TranscriptionFrame,
    FunctionCallInProgressFrame,
    TTSSpeakFrame,
)
from pipecat.pipeline.pipeline import Pipeline
from pipecat.processors.frame_processor import FrameDirection, FrameProcessor
from pipecat.pipeline.worker import PipelineParams, PipelineWorker
from pipecat.processors.aggregators.llm_context import LLMContext
from pipecat.processors.aggregators.llm_response_universal import (
    LLMContextAggregatorPair,
    LLMUserAggregatorParams,
)
from pipecat.runner.types import RunnerArguments
from pipecat.runner.utils import create_transport
from pipecat.processors.frameworks.rtvi import RTVIObserverParams, RTVIFunctionCallReportLevel
from providers.llm.factory import get_llm
from providers.stt.factory import get_stt
from providers.tts.factory import get_tts
from pipecat.transports.base_transport import BaseTransport, TransportParams
from pipecat.transports.daily.transport import DailyParams
from pipecat.workers.runner import WorkerRunner
from pipecat.turns.user_turn_strategies import UserTurnStrategies, TurnAnalyzerUserTurnStopStrategy
from services.memory import build_memory_messages, build_turn_memory_context, hydrate_memory_bundle, load_session_bundle, save_conversation_message
from core.memory_config import MEMORY_EMBEDDING_DIMENSION
from services.rag import (
    build_rag_context_with_payload,
    is_rag_query,
    prime_rag_corpus_status,
    user_has_ready_rag_corpus,
)
from core.rag_config import RAG_VOICE_QUERY_WINDOW_SECONDS
from core.voice_config import load_endpointing_config, startup_greeting
from core.voice_services import initialize_voice_runtime
from core.audio_config import audio_input_sample_rate, audio_out_10ms_chunks, audio_output_sample_rate
from core.turn_analyzer import (
    SharedModelSileroVADAnalyzer,
    SharedModelSmartTurnAnalyzerV3,
    warm_silero_vad_model,
    warm_smart_turn_model,
)
from core.admission import voice_admission
from core.latency_observer import PipelineLatencyObserver, event_loop_lag_monitor
from core.realtime_gate import realtime_turn_gate
from tools.tavily import run_web_search, tavily_search
from tools.raise_issue import raise_issue

load_dotenv(override=True)

from core.processors import (
    ConversationMemoryProcessor,
    ToolFillerProcessor,
    ContextRetrievalProcessor,
    LeadingSilenceTrimmerProcessor,
    TurnContextCleanupProcessor,
    TurnLatencyState,
    LatencyBoundaryProcessor,
    BoundedContextProcessor,
    ToolRoutingProcessor,
    transport_server_message,
)


async def run_bot(transport: BaseTransport, runner_args: RunnerArguments) -> None:
    """Run the voice bot for this session.

    Args:
        transport: The transport for this session, built by ``create_transport``
            (or by hand for the dial-out/SIP production flows).
        runner_args: Runner session arguments. Carries the request ``body``
            (e.g. dial-out settings, SIP call details) and ``session_id``; the
            standard web/telephony pipelines don't need it.
    """
    logger.info("Starting bot")

    # Constructors may load ONNX/Piper models or initialize provider clients.
    # They are independent, so keep them off the event loop and overlap them.
    (stt, tts, llm), memory_bundle = await initialize_voice_runtime(
        get_stt, get_tts, get_llm,
        load_session_bundle, runner_args.body,
    )
    # Warm OpenAI-compatible provider networking while the rest of the
    # session pipeline is assembled. This uses the same client instance that
    # will serve the first turn and fails open inside the provider.
    llm_warmup_task = None
    warm_connection = getattr(llm, "warm_connection", None)
    if callable(warm_connection):
        llm_warmup_task = asyncio.create_task(
            warm_connection(), name="voice-llm-connection-warmup"
        )
    memory_messages = build_memory_messages(memory_bundle)
    if memory_bundle:
        logger.info(
            f"Loaded memory for user={memory_bundle.user.id} "
            f"conversation={memory_bundle.conversation.id} "
            f"facts={len(memory_bundle.facts)} recent_messages={len(memory_bundle.recent_messages)}"
        )
    conversation_id = memory_bundle.conversation.id if memory_bundle else None
    user_id = memory_bundle.user.id if memory_bundle else None
    if memory_bundle:
        prime_rag_corpus_status(user_id, memory_bundle.has_ready_rag_corpus)
    assistant_memory = ConversationMemoryProcessor(
        conversation_id,
        capture="assistant",
        name="AssistantMemory",
    )

    context = LLMContext(
        messages=memory_messages,
        tools=[]
    )
    context_window = BoundedContextProcessor(
        context,
        protected_messages=memory_messages,
        max_messages=int(os.getenv("VOICE_CONTEXT_MAX_MESSAGES", "12")),
        max_chars=int(os.getenv("VOICE_CONTEXT_MAX_CHARS", "6000")),
        name="BoundedContext",
    )

    async def install_optional_memory():
        if not memory_bundle:
            return
        try:
            hydrated = await hydrate_memory_bundle(memory_bundle)
        except asyncio.CancelledError:
            raise
        except Exception as exc:
            logger.warning("Optional session memory hydration failed: {!r}", exc)
            return
        hydrated_messages = build_memory_messages(hydrated)
        if not hydrated_messages:
            return
        if any(message.get("role") == "user" for message in context.messages if isinstance(message, dict)):
            logger.info("Optional session memory arrived after first user turn; skipping foreground install")
            return
        context.messages[0:0] = hydrated_messages
        context_window.protect_messages(hydrated_messages)
        logger.info("Installed {} asynchronously hydrated memory messages", len(hydrated_messages))

    memory_hydration_task = asyncio.create_task(install_optional_memory())
    latency_state = TurnLatencyState(
        session_id=getattr(runner_args, "session_id", None),
        llm_provider=os.getenv("LLM_PROVIDER", "google").strip().lower(),
        llm_model=getattr(getattr(llm, "_settings", None), "model", None),
        tts_provider=os.getenv("TTS_PROVIDER", "cartesia").strip().lower(),
        tts_model=getattr(getattr(tts, "_settings", None), "model", None),
        llm_warm_state_getter=lambda: bool(
            getattr(llm, "connection_warmed", False)
        ),
    )
    context_retrieval = ContextRetrievalProcessor(
        user_id,
        conversation_id,
        context,
        latency_state,
        web_search=run_web_search,
        ready_corpus_check=user_has_ready_rag_corpus,
        name="ContextRetrieval",
    )
    tool_router = ToolRoutingProcessor(
        context,
        search_tool=tavily_search,
        issue_tool=raise_issue,
        retrieval=context_retrieval,
        latency_state=latency_state,
        name="ToolRouter",
    )
    context_cleanup = TurnContextCleanupProcessor(
        context_retrieval, latency_state, name="TurnContextCleanup"
    )
    endpointing = load_endpointing_config()
    logger.info(
        "voice_endpointing vad_confidence={} vad_start_secs={} vad_stop_secs={} "
        "vad_min_volume={} smart_turn_stop_secs={}",
        endpointing.vad_confidence,
        endpointing.vad_start_secs,
        endpointing.vad_stop_secs,
        endpointing.vad_min_volume,
        endpointing.smart_turn_stop_secs,
    )
    user_turn_strategies = UserTurnStrategies(
        stop=[
            TurnAnalyzerUserTurnStopStrategy(
                turn_analyzer=SharedModelSmartTurnAnalyzerV3(
                    params=SmartTurnParams(
                        stop_secs=endpointing.smart_turn_stop_secs,
                        pre_speech_ms=endpointing.smart_turn_pre_speech_ms,
                        max_duration_secs=endpointing.smart_turn_max_duration_secs,
                    )
                )
            )
        ]
    )
    user_aggregator, assistant_aggregator = LLMContextAggregatorPair(
        context,
        user_params=LLMUserAggregatorParams(
            vad_analyzer=SharedModelSileroVADAnalyzer(
                params=VADParams(
                    confidence=endpointing.vad_confidence,
                    start_secs=endpointing.vad_start_secs,
                    stop_secs=endpointing.vad_stop_secs,
                    min_volume=endpointing.vad_min_volume,
                )
            ),
            user_turn_strategies=user_turn_strategies,
        ),
    )

    @user_aggregator.event_handler("on_user_turn_started")
    async def reset_query_scoped_turn_state(aggregator, strategy):
        context_retrieval.start_user_turn()

    @user_aggregator.event_handler("on_user_turn_stopped")
    async def persist_complete_user_turn(aggregator, strategy, message):
        content = (message.content or "").strip()
        if content:
            from core.task_queue import task_queue
            task_queue.enqueue(
                save_conversation_message,
                conversation_id,
                "You",
                content,
                key=conversation_id,
            )

    tool_filler = ToolFillerProcessor(latency_state, name="ToolFiller")

    # Pipeline - assembled from reusable components
    pipeline = Pipeline(
        [
            transport.input(),
            LatencyBoundaryProcessor(latency_state, "vad", name="PostVADLatency"),
            stt,
            LatencyBoundaryProcessor(latency_state, "stt", name="PostSTTLatency"),
            user_aggregator,
            LatencyBoundaryProcessor(latency_state, "turn", name="PostTurnLatency"),
            context_retrieval,
            tool_router,
            context_window,
            llm,
            LatencyBoundaryProcessor(latency_state, "llm", name="PostLLMLatency"),
            context_cleanup,
            tool_filler,
            assistant_memory,
            tts,
            LeadingSilenceTrimmerProcessor(name="LeadingSilenceTrimmer"),
            LatencyBoundaryProcessor(latency_state, "tts", name="PostTTSLatency"),
            transport.output(),
            assistant_aggregator,
        ]
    )

    worker = PipelineWorker(
        pipeline,
        params=PipelineParams(
            enable_metrics=True,
            enable_usage_metrics=True,
        ),
        rtvi_observer_params=RTVIObserverParams(
            # Tool lifecycle UI events are emitted explicitly so filler always
            # appears first and provider-specific frame direction cannot hide them.
            function_call_report_level={"*": RTVIFunctionCallReportLevel.DISABLED}
        ),
        app_resources={"latency_state": latency_state},
        observers=[PipelineLatencyObserver()],
    )

    @worker.rtvi.event_handler("on_client_ready")
    async def on_client_ready(rtvi):
        # A greeting does not require model reasoning. Keeping it out of the
        # LLM path removes startup TTFT and avoids a permanent prompt message.
        startup_frames = []
        if conversation_id:
            startup_frames.append(OutputTransportMessageFrame({
                "label": "rtvi-ai",
                "type": "server-message",
                "data": {
                    "type": "conversation_ready",
                    "payload": {"conversation_id": conversation_id},
                },
            }))
        greeting = startup_greeting()
        if greeting:
            startup_frames.append(transport_server_message(
                "assistant_transcript",
                {
                    "id": "startup-greeting",
                    "text": greeting,
                    "source": "greeting",
                },
            ))
            startup_frames.append(TTSSpeakFrame(greeting, append_to_context=False))
        if startup_frames:
            await worker.queue_frames(startup_frames)

    @transport.event_handler("on_client_connected")
    async def on_client_connected(transport, client):
        logger.info("Client connected")

    @transport.event_handler("on_client_disconnected")
    async def on_client_disconnected(transport, client):
        logger.info("Client disconnected")
        await worker.cancel()

    runner = WorkerRunner(handle_sigint=False)

    try:
        if llm_warmup_task:
            await llm_warmup_task
            latency_state.llm_connection_warmed = bool(
                getattr(llm, "connection_warmed", False)
            )
        await runner.add_workers(worker)
        await runner.run()
    finally:
        realtime_turn_gate.end(latency_state.priority_key)
        if llm_warmup_task and not llm_warmup_task.done():
            llm_warmup_task.cancel()
        if not memory_hydration_task.done():
            memory_hydration_task.cancel()
        await asyncio.gather(
            memory_hydration_task,
            *(tuple([llm_warmup_task]) if llm_warmup_task else ()),
            return_exceptions=True,
        )


async def bot(runner_args: RunnerArguments):
    """Main bot entry point."""

    if not await voice_admission.try_acquire():
        logger.warning(
            "voice_admission status=rejected active={} limit={} session={}",
            voice_admission.active,
            voice_admission.limit,
            getattr(runner_args, "session_id", None),
        )
        raise RuntimeError("voice session capacity reached")

    try:
        output_chunks = audio_out_10ms_chunks()
        input_sample_rate = audio_input_sample_rate()
        output_sample_rate = audio_output_sample_rate()
        transport_params = {
            "daily": lambda: DailyParams(
                audio_in_enabled=True,
                audio_in_sample_rate=input_sample_rate,
                audio_out_enabled=True,
                audio_out_sample_rate=output_sample_rate,
                audio_out_10ms_chunks=output_chunks,
            ),
            "webrtc": lambda: TransportParams(
                audio_in_enabled=True,
                audio_in_sample_rate=input_sample_rate,
                audio_out_enabled=True,
                audio_out_sample_rate=output_sample_rate,
                audio_out_10ms_chunks=output_chunks,
            ),
        }

        transport = await create_transport(runner_args, transport_params)
        await run_bot(transport, runner_args)
    finally:
        await voice_admission.release()


from fastapi import APIRouter, HTTPException
from sqlalchemy import text
from core.database import engine
health_router = APIRouter(tags=["health"])

@health_router.get("/health/live")
async def liveness_probe():
    return {"status": "alive"}

@health_router.get("/health/ready")
async def readiness_probe():
    from core.task_queue import task_queue
    from core.readiness import validate_voice_provider_configuration

    if not task_queue.is_running:
        raise HTTPException(status_code=503, detail="background workers are not ready")

    try:
        providers = validate_voice_provider_configuration()
    except ValueError as exc:
        logger.warning("readiness voice provider configuration failed: {}", exc)
        raise HTTPException(status_code=503, detail=f"voice providers are not ready: {exc}") from exc

    async def check_database():
        async with engine.connect() as connection:
            await connection.execute(text("SELECT 1"))

    try:
        await asyncio.wait_for(check_database(), timeout=1.5)
    except Exception as exc:
        logger.warning("readiness database check failed: {}", exc)
        raise HTTPException(status_code=503, detail="database is not ready") from exc

    return {
        "status": "ready",
        "database": "ready",
        "workers": "ready",
        "voice_providers": providers,
    }



if __name__ == "__main__":
    from core.logging_config import configure_nonblocking_logging
    configure_nonblocking_logging()
    from pipecat.runner.run import app, main
    from fastapi.middleware.cors import CORSMiddleware
    from fastapi.responses import JSONResponse
    import os

    allowed_origins_str = os.getenv("ALLOWED_ORIGINS", "http://localhost:5173,http://localhost:80")
    allowed_origins = [origin.strip() for origin in allowed_origins_str.split(",")]

    app.add_middleware(
        CORSMiddleware,
        allow_origins=allowed_origins,
        allow_credentials=True,
        allow_methods=["*"],
        allow_headers=["*"],
    )

    @app.middleware("http")
    async def reject_over_capacity(request, call_next):
        path = request.url.path
        starts_voice = request.method == "POST" and (
            path == "/start" or path == "/api/offer" or path.endswith("/api/offer")
        )
        if starts_voice and not voice_admission.has_capacity:
            return JSONResponse(
                status_code=503,
                content={"detail": "voice capacity reached; retry shortly"},
                headers={"Retry-After": "2"},
            )
        return await call_next(request)

    from api.auth import router as auth_router
    from api.history import router as history_router
    from api.memories import router as memories_router
    from api.rag_files import router as rag_files_router
    from api.telemetry import router as telemetry_router
    
    app.include_router(auth_router)
    app.include_router(history_router)
    app.include_router(memories_router)
    app.include_router(rag_files_router)
    app.include_router(telemetry_router)
    app.include_router(health_router)
    
    from contextlib import asynccontextmanager
    
    # Initialize the background task queue
    @asynccontextmanager
    async def lifespan(app):
        from core.task_queue import task_queue
        from core.database import warm_voice_pool
        # pipecat.runner.run.main() installs its own synchronous DEBUG sink
        # immediately before Uvicorn starts. Reassert the bounded production
        # sink here, after that override and before latency-critical work.
        configure_nonblocking_logging(force=True)
        await asyncio.gather(
            asyncio.to_thread(warm_smart_turn_model),
            asyncio.to_thread(warm_silero_vad_model),
            warm_voice_pool(int(os.getenv("DB_VOICE_WARM_CONNECTIONS", "2"))),
        )
        event_loop_lag_monitor.start()
        task_queue.start(num_workers=3)
        yield
        await task_queue.stop()
        await event_loop_lag_monitor.stop()

    app.router.lifespan_context = lifespan

    main()
