"""initial

Revision ID: 3c5c3ec4e525
Revises: 
Create Date: 2026-07-15 18:23:01.089400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c5c3ec4e525'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_memory_chunks_embedding'), table_name='memory_chunks', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.drop_index(op.f('idx_rag_chunks_embedding'), table_name='rag_chunks', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.drop_index(op.f('idx_rag_chunks_search_vector'), table_name='rag_chunks', postgresql_using='gin')
    op.drop_index(op.f('idx_rag_chunks_user_file'), table_name='rag_chunks')
    op.drop_index(op.f('idx_rag_files_user_status'), table_name='rag_files')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_rag_files_user_status'), 'rag_files', ['user_id', 'status'], unique=False)
    op.create_index(op.f('idx_rag_chunks_user_file'), 'rag_chunks', ['user_id', 'file_id'], unique=False)
    op.create_index(op.f('idx_rag_chunks_search_vector'), 'rag_chunks', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_rag_chunks_embedding'), 'rag_chunks', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.create_index(op.f('idx_memory_chunks_embedding'), 'memory_chunks', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    # ### end Alembic commands ###
